site_name: JLU 規則書

theme:
  name: material
  language: zh-TW # 設定語言為繁體中文，搜尋功能對中文支援會更好
  features:
    - navigation.tabs # 在畫面上方加入導航頁籤
    - navigation.top # 加入「回到最上方」按鈕
    - search.suggest # 搜尋關鍵字建議
  palette:
    # 淺色模式設定
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo # 頂部導航列顏色 (深藍)
      accent: blue    # 連結與按鈕顏色
      toggle:
        icon: material/weather-night
        name: 切換至深色模式
    # 深色模式設定
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: 切換至淺色模式

nav:
  - 導論與核心概念: JLU_譯文_01_導論與核心概念.md
  - 角色創建:
      - 位階、PAX與屬性: JLU_譯文_03_角色創建_位階PAX屬性.md
      - 出身與原型: JLU_譯文_04_出身與原型.md
  - 能力與裝備:
      - 能力總則與武術訓練: JLU_譯文_05_能力總則與武術訓練.md
      - 超能力: JLU_譯文_06_超能力.md
      - 科技、知識、裝備與特質限制: JLU_譯文_07_科技知識裝備特質限制.md
  - 戰鬥與判定:
      - 檢定與戰鬥基礎: JLU_譯文_08_檢定與戰鬥基礎.md
      - 狀態、移動與戰鬥動作: JLU_譯文_09_狀態移動與戰鬥動作.md
  - 專有名詞對應表: JLU_專有名詞對應表_v2.md
  - 劇情點與編輯點與危機骰: JLU_譯文_02_劇情點與編輯點與危機骰.md
plugins:
  - search:
      lang: zh